#!/bin/bash
# Setup guide for Docker with window display
# This script helps configure Docker to display windows

echo "=== Docker Window Display Setup Guide ==="
echo ""

echo "📋 Prerequisites (on host machine, BEFORE starting Docker):"
echo ""
echo "1. Install X11 utilities (if not already installed):"
echo "   sudo apt-get update"
echo "   sudo apt-get install x11-xserver-utils xauth"
echo ""
echo "2. Allow X11 connections:"
echo "   xhost +local:root"
echo "   # Or more securely:"
echo "   xhost +SI:localuser:root"
echo ""
echo "3. Check DISPLAY variable:"
echo "   echo \$DISPLAY"
echo "   # Should output something like :0 or :10.0"
echo ""
echo "4. Verify X11 socket exists:"
echo "   ls -la /tmp/.X11-unix/"
echo ""
echo "=========================================="
echo ""
echo "📋 Docker Run Command (use these flags):"
echo ""
echo "docker run --name internnav -it --rm \\"
echo "  --gpus all \\"
echo "  --network host \\"
echo "  -e \"DISPLAY=\${DISPLAY}\" \\"
echo "  -e \"ACCEPT_EULA=Y\" \\"
echo "  -e \"PRIVACY_CONSENT=Y\" \\"
echo "  -e \"QT_X11_NO_MITSHM=1\" \\"
echo "  --entrypoint /bin/bash \\"
echo "  -w /root/InternNav \\"
echo "  -v /tmp/.X11-unix/:/tmp/.X11-unix:rw \\"
echo "  -v \${PWD}:/root/InternNav \\"
echo "  your-image:tag"
echo ""
echo "=========================================="
echo ""
echo "📋 Inside Docker Container:"
echo ""
echo "1. Verify DISPLAY is set:"
echo "   echo \$DISPLAY"
echo ""
echo "2. Test X11 connection:"
echo "   xeyes  # Should open a window (if xeyes is installed)"
echo ""
echo "3. Set additional environment variables if needed:"
echo "   export QT_X11_NO_MITSHM=1"
echo "   export MESA_GL_VERSION_OVERRIDE=4.5"
echo ""
echo "=========================================="
echo ""
echo "⚠️  Troubleshooting:"
echo ""
echo "If you see 'Cannot connect to X server':"
echo "  1. Check xhost on host: xhost"
echo "  2. Ensure DISPLAY is set in container"
echo "  3. Verify /tmp/.X11-unix is mounted"
echo ""
echo "If windows don't appear:"
echo "  1. Check if X server is running on host"
echo "  2. Try using Xvfb for virtual display (headless alternative)"
echo "  3. Use VNC or X11 forwarding via SSH"








